development:
  adapter: postgresql
  encoding: utf8
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5
  timeout: 5000
  database: spectre_development

test: &test
  adapter: postgresql
  encoding: utf8
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5
  timeout: 5000
  database: spectre_test

cucumber:
  adapter: postgresql
  encoding: utf8
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
